In [2]:
import os 
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [26]:
class Perceptron:
    def __init__(self,eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iteration
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones(len(self.X))]
        print(f"X With bias :\n {X_with_bias}")

In [27]:
obj = Perceptron(eta = 0.01,epochs = 4)

In [28]:
obj.eta

0.01

In [29]:
obj.epochs

4

In [30]:
obj.weights

array([-1.44267612e-04, -5.78077275e-05, -5.40167743e-05])

In [31]:
X = np.ones((4,2))

In [32]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [34]:
obj.fit(X,y)

X With bias :
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
