In [1]:
import os 
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")

In [50]:
class Perceptron:
    def __init__(self,eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iteration
    
    def _z_outcomes(self, inputs, weights):
        return np.dot(inputs, weights)
        
    def activation_function(self,z):
        return np.where(z >0, 1, 0)
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X With bias :\n {X_with_bias}")
        
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)

            z = self._z_outcomes(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
    
    
    
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcomes(X_with_bias, self.weights)
        return self.activation_function(z)
    
    

In [19]:
obj = Perceptron(eta = 0.01,epochs = 4)

In [20]:
obj.eta

0.01

In [21]:
obj.epochs

4

In [22]:
obj.weights

array([-6.02627800e-05, -1.38472393e-04, -1.92587258e-04,  2.87862268e-04])

In [70]:
X = np.ones((4,2))

In [71]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [43]:
obj.fit(X,y)

X With bias :
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [51]:
 OR = {
     "x1":[0,0,1,1],
     "x2":[0,1,0,1],
     "y" : [0,1,1,1],
 }
    
df_OR = pd.DataFrame(OR)
df_OR


x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [52]:
def prepare_data(df, target_col = "y"):
    X = df_OR.drop(target_col,axis= 1)
    y = df_OR[target_col]
    return X,y

In [53]:
X,y = prepare_data(df_OR)
X
ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta = ETA, epochs =EPOCHS)

model_or.fit(X,y)

X With bias :
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 1 0 1]
error: 
0    0
1    0
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 1.00023394e-01  9.90265060e-05 -9.99382379e-02]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[1.00023394e-01 9.90265060e-05 6.17621357e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[1.00023394e-01 9.90265060e-05 6.17621357e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   

In [48]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [49]:
model_or.predict(X)

array([0, 1, 1, 1])